
plaid:
  institutionid: "ins_3"
  clientid: "5d2eaa07005af000125f307d"
  publickey: "c5f2d27962a2401407b5566385a512"
  secret: "98ef86bbda9e92e77c04fec6fe69b4"
  username: ENC(A/fiqd748HkuAmcN/UOqBv/qbmJikqlp)
  password: ENC(Otjf6vrPno9/mFiWX8kZ4npKOW8hRdTV)

bigbrother:
  host: localhost:8081

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    password:
    dbname: testdb

